### ISSUE TITLE
Field Level Mapping defaults are incorrect

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#142]
Default settings & chart in latest `dev-v0.7.0` build shown below.

![11_55_24](https://user-images.githubusercontent.com/3680095/51936447-0e774780-23bd-11e9-99a5-8e8e6da8e054.jpg)
![11_55_37](https://user-images.githubusercontent.com/3680095/51936450-0f0fde00-23bd-11e9-990c-3d4f71395566.jpg)

**Comment by pburnsdata** [comment]
right now when the spec is not full -> the chart doesn't try to guess the default field level mappings so it populates with the first option (potassium). Random thoughts: We could guess these values for partial specs if the measure col is present (instead of using the first option). Also brings up whether these should be required cols- and then would update the partial spec match to include these
