### ISSUE TITLE
validateSettings() produces duplicates

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#61]
Example code:
```
settingsl <- list(id_col = "USUBJID",
                  value_col = "AVAL", 
                  measure_col = "PARAM", 
                  visit_col = "VISIT",
                  visitn_col = "VISITNUM",
                  studyday_col = "ADY", 
                  normal_col_low = "A1LO", 
                  normal_col_high = "A1HI", 
                  measure_values = list(ALT = "Alanine Aminotransferase (U/L)",
                                        AST = "Aspartate Aminotransferase (U/L)",
                                        TB = "Bilirubin (umol/L)",
                                        ALP = "Alkaline Phosphatase (U/L)"))

s <- validateSettings(adlbc, settingsl)
```

Output:
![image](https://user-images.githubusercontent.com/14199771/48791277-58f28e80-ecbf-11e8-9810-1e0ff68db1b9.png)

All "text_key"s represented:
![image](https://user-images.githubusercontent.com/14199771/48791373-92c39500-ecbf-11e8-9d50-2e771cda120c.png)

**Comment by jwildfire** [comment]
This is somewhat confusing, but the 2 checks are doing different things, so the behaviour is expected. The first check in the list above is confirming that required settings (of any type, data mapping or otherwise) are not null. The second check is confirming that any non-null data-mapping settings have matching columns in the data set.
