### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by mmz2001** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#704]
I got the following error when I tried to install it in RStudio Pro. Is there a remedy?  

  Error: object ‘markdownExtensions’ is not exported by 'namespace:markdown'
  Execution halted
  ERROR: lazy loading failed for package ‘safetyGraphics’

**Comment by jwildfire** [comment]
@bzkrouse @nandriychuk @samussiah @xni7 Anyone seen an error like this one before? It's new to me ...

**Comment by jwildfire** [comment]
Hmm. I looked a bit and `markdownExtensions` was [removed from the markdown package late last year](https://github.com/rstudio/markdown/blob/master/NEWS.md). That said, I don't think we're using the `markdownExtensions` function or even the `markdown` package in safetyGraphcis. We do use the `rmarkdown` package, so maybe there's a dependency there ... it doesn't look like it though. Not sure. Could be used as a dependency for something else ... 

My best guess is that there is an issue with the way RStudio Pro is building the vignettes or the roxygen headers. You might try installing without building the vignettes ... I guess as a last resort you could try installing markdown v1.3 so that the missing function will be found. 

I'm going to close this for now, but feel free to re-open if you find any more details and we can help with an update to the package.
