### ISSUE TITLE
Set up Travis CI integration

### ISSUE THREAD

**Issue by jwildfire** [ASA-DIA-InteractiveSafetyGraphics/safetyGraphics#76]
Both the unit tests and the shiny tests should be run after each commit. All tests should be required to pass before merging to master.

**Comment by jwildfire** [comment]
Summary of progress so far: All standard `testthat`tests are working as expected. `shinytest' tests are failing. Scattered notes below: 

- need to make sure we are actually installing shiny on the travis server
- The current issue `shinytest` is almost definitely a in the .travis.yaml configuration. It looks to me like the system can't actually run the app ... so the test fails at that point without actually running. 
- adding `r:3.4.4` to the yaml file is a good start
- we should consider using `packrat` to speed up the travis process (pretty sure the cache) function is ignored now. 
- should consider moving to `os:osx` so that the image compare will work (if we create images on my machine)

**Comment by pburnsdata** [comment]
The Travis CI is currently up and running and is using packrat
Notes:
- I did not add the shinytest tests because the debugging seemed like it was going to take too long. Going to make a separate issue for that
- I did not change the os to osx or windows, because we are not using the shinytests currently and I feared that that commands to create phantomJS were written fro linux and would not work when the os changed.
